name: Tests

on:
  push:
      branches:
        - develop

jobs: 
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify dependencies
        run: |
          pip check

      - name: Check pytest installation
        run: |
          pytest --version

      - name: Check black installation
        run: |
          black --version

      - name: Check isort installation
        run: |
          isort --version

      - name: Check pylint installation
        run: |
          pylint --version

      - name: Run tests
        run: |
          pytest

      - name: Post success message
        if: success()
        run: echo "All tests passed successfully on Python ${{ matrix.python-version }}!"

      - name: Post failure message
        if: failure()
        run: echo "Tests failed on Python ${{ matrix.python-version }}. Please check the logs for details."